### PR TITLE
Update to UE 4.21

### PR DESCRIPTION
**Pull request by umbah**
Required changes to header files, module and path handling for UE 4.21 compatibility

Tested with:

- G27
- UE4 Version  4.21.2-4753647+++UE4+Release-4.21, binary distribution from Epic.
- Built using the runuat command line script
- CL 19.16.27027.1 (x64)

### CODE REVIEW

**Comment by xugg01** [comment]
233

**Comment by active-game** [comment]
You guys are great !!!  Thank you, but I beg you to upgrade to version 4.22

**Comment by fortune1990** [comment]
any chance of a UE 5.1 or newer version Thanks

**Comment by umbah** [comment]
> any chance of a UE 5.1 or newer version Thanks
See https://github.com/drb1992/LogitechWheelPlugin/issues/3#issuecomment-1935297225

**Pull request merged**
